### ISSUE TITLE
Hooks Postgres Password

### ISSUE THREAD

**Issue by RXminuS** [polyaxon/polyaxon-chart#28]
The password is set to `POLYAXON_DB_USER` but should be read from the password secret  or `POLYAXON_DB_PASSWORD` instead. It doesn't seem to exist in the config map though so not quite sure how you would like me to fix this.

https://github.com/polyaxon/polyaxon-chart/blob/02d740f7eb2e730976e9c55efa284d8061135a70/polyaxon/templates/hooks/tables-job.yaml#L43

**Comment by mouradmourafiq** [comment]
Good catch.

**Comment by mouradmourafiq** [comment]
I just updated it, thanks again. The issue went unnoticed because the default values for user and password are the same.

**Comment by mouradmourafiq** [comment]
@RXminuS We updated our guides page, please let me know when your blog post is up, and I will link to it in our guides page.

Thanks.
