### ISSUE TITLE
Error: requirements.lock is out of sync with requirements.yaml

### ISSUE THREAD

**Issue by bnouvel-wio** [polyaxon/polyaxon-chart#34]
Issue: I was trying to install polyaxon with helm in an automated environment, install did fail with message : 
"""Error: requirements.lock is out of sync with requirements.yaml"""

While issue can easily be solved manually "in manual deployments", 
it would be good for automation to update the lock file in the repository.

**Comment by mouradmourafiq** [comment]
Can you please share the command/way used for deploying the chart?
