### ISSUE TITLE
gitlab oauth

### ISSUE THREAD

**Issue by jmvizcainoio** [polyaxon/polyaxon-chart#50]
I can see that the chart was compatible with gitlab auth in the past, but now I'm not sure if it is compatible or only ldap.

Can you clarify it for me?

Thank you

Juanma

**Comment by mouradmourafiq** [comment]
Sorry about late response, I must have missed the notification. 
You can enable gitlab for auth after deploying the platform, the settings is on the UI page: `dropdown > settings > auth`.
